# Configuración de conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/academia
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Inicialización del esquema de Spring Batch
spring.batch.jdbc.initialize-schema=always

# Ejecutar el Job al arrancar
spring.batch.job.enabled=true

# Configuración de conexión a MongoDB
spring.data.mongodb.uri=mongodb://root:root123@localhost:27018/academia?authSource=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true